app/__init__.py
from flask import Flask
from .config import Config
from .routes.zero import zero

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    app.register_blueprint(zero)

    return app

app/routes/zero.py
from flask import Blueprint, render_template, redirect, flash
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerRangeField, BooleanField
import random
import string

zero = Blueprint('zero', __name__)

class GeneratedPassword(FlaskForm):
    password_text = StringField('Example', id='password-value')
    password_length = IntegerRangeField('Size', render_kw={"min": 6, "max": 66}, id='password-len')
    include_lowercase = BooleanField('Include lowercase', id='include_lowercase')
    include_uppercase = BooleanField('Include uppercase')
    include_numbers = BooleanField('Include numbers')
    include_symbols = BooleanField('Include symbols')
    # generate_password = SubmitField('', id='generate')

def generate(length, use_lower=True, use_upper=True, use_digits=True, use_punctuation=True):
    characters = ""
    if use_lower:
        characters += string.ascii_lowercase
    if use_upper:
        characters += string.ascii_uppercase
    if use_digits:
        characters += string.digits
    if use_punctuation:
        characters += string.punctuation

    passw = ''.join(random.choice(characters) for i in range(length))
    
    return passw

@zero.route('/')
def index():
    return redirect('/password')

@zero.route('/password', methods=['GET', 'POST'])
def pass_generator():
    password = GeneratedPassword()

    if password.is_submitted():
        use_lower = password.include_lowercase.data
        use_upper = password.include_uppercase.data
        use_numbers = password.include_numbers.data
        use_symbols = password.include_symbols.data
        password_length = password.password_length.data

        if use_upper == False and use_lower == False and use_numbers == False and use_symbols == False:
            flash(f'Please, choose an option', category='danger')
            password.password_text.data = 'Choose an option'
        else:
            final_password = generate(password_length, use_lower, use_upper, use_numbers, use_symbols)
            password.password_text.data = final_password

    context = {
        'password': password
    }

    return render_template('zero.html', **context)

app/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/password.png') }}">
    <meta name="google-site-verification" content="8Gu2Ym2jGwxk2cTWI1DwrlmRPLS37W2b4PTOvIcLV6k" />

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/zero.css') }}">
    <!-- CSS Frameworks -->
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.15.21/dist/css/uikit.min.css" />

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.15.21/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.15.21/dist/js/uikit-icons.min.js"></script>

    <!-- Font Awesome CSS -->
    <script src="https://kit.fontawesome.com/4fdf46b80d.js" crossorigin="anonymous"></script>
    
    <title>ZeroPass</title>
</head>

<body class="uk-flex uk-flex-column uk-flex-center uk-flex-middle ">
    {% block content %}

    {% endblock %}
    <script src="{{ url_for('static', filename='js/password_length.js') }}"></script>
</body>

</html>

app/templates/zero.html
{% extends 'base.html'%}
{% block content %}
    <div class="uk-card uk-card-default uk-card-small card">

        <div class="uk-card-header uk-flex uk-flex-column uk-flex-middle" style="border-bottom: 0; padding-top: 40px;">
            <img src="{{ url_for('static', filename='img/password.png') }}" alt="Zero" width="60" height="60">
            <span class="title">Zero<b>Pass</b></span>
            <span class="subtitle">Password Generator</span>
        </div>

        <div class="uk-card-body uk-card-small uk-flex uk-flex-column uk-flex-middle">
            <form class="uk-form-horizontal uk-margin-large form-style" action="{{ url_for('zero.pass_generator') }}" method="post">
                <div class="uk-margin">
                    <div class="uk-inline">
                        <a id="copy" class="uk-form-icon uk-form-icon-flip" onclick="copyPassword()" uk-tooltip="Copy"><i class="fa-regular fa-clone"></i></a>
                        {{ password.password_text(class="uk-input", placeholder="Password") }}
                    </div>
                    <button id="generate" class="uk-button uk-button-default generar"><i class="fa-solid fa-arrows-rotate"></i></button>
                </div>
                <div class="uk-margin" uk-margin>
                    <div class="space">
                        <label class="uk-form-label" for="password-len">Password length:</label>
                        <span id="range-value" class="uk-badge"></span>
                    </div>
                    {{ password.password_length(class="uk-range", placeholder="") }}
                </div>
                <div class="uk-form-toggle space">
                    <label for="include_lowercase" class="text-style">Include lowercase:</label>
                    {{ password.include_lowercase(class="uk-checkbox swith-style") }}
                </div>
                <div class="uk-form-toggle space">
                    <label for="" class="text-style">Include uppercase:</label>
                    {{ password.include_uppercase(class="uk-checkbox") }}
                </div>
                <div class="uk-form-toggle space">
                    <label for="" class="text-style">Include numbers:</label>
                    {{ password.include_numbers(class="uk-checkbox") }}
                </div>
                <div class="uk-form-toggle space">
                    <label for="" class="text-style">Include symbols:</label>
                    {{ password.include_symbols(class="uk-checkbox") }}
                </div>
            </form>
        </div>
        
        <div class="uk-card-footer footer" style="border-top: 0;">
            <span class="">Hecho con &#128150; por <b><a href="https://github.com/Sebas1012" target="_blank">sebas1012</a></b>.</span>
        </div>
    </div>
{% endblock %}